### ISSUE TITLE
Email - Fallback to hostname for admin email address

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#10217]
**Check what happens in 4.8 first with a missing admin_email first - if it's not hostname then update this issue**

4.9 upgraded the [symfony mailer](https://docs.silverstripe.org/en/4/changelogs/4.9.0/#swiftmailer) 

As part of this symfony stopped sending emails with a 'From' address

This is set via 

```yml
SilverStripe\Control\Email\Email:
  admin_email: 'no-reply@mysite.com'
```

This is often set via yml that copied over from installer recipes.

Sites that do no have this configuration used to work prior to 4.9, though upon upgrading many have stopped sending emails

Because of this, fallback to setting this to `no-reply@[hostname]`

Remember to add a unit test :-)

Fix for this needs to target `4.9` and be merged up.  Release new versions of 4.9.x and 4.10.x

Note recipe-cms 4.9.0 has `~` requirements so users of this can easily receive this fix

# ACs
- [x] Validate what used to happen on 4.8
- [x] The generated email does not expose key server info
- [x] A sensible default has been identified and implemented.
- [x] Tag a new version of 4.9
- [x] Tag a new version of 4.10

# PRs
- [x] https://github.com/silverstripe/silverstripe-framework/pull/10236
- [x] https://github.com/silverstripe/silverstripe-framework/pull/10251
- [x] https://github.com/silverstripe/silverstripe-framework/pull/10252

# Post-merge
- [x] Merge-up
- [x] Add `$this->extend('updateDefaultFrom', $defaultFrom);` to the bottom of `Email::getDefaultFrom()` in a PR targetting `4`

**Comment by emteknetnz** [comment]
Likely update code here
https://github.com/silverstripe/silverstripe-framework/blob/4/src/Control/Email/Email.php#L279

**Comment by maxime-rainville** [comment]
Just to summarise some of the discussions we've been having, reveling the host name of the server might not be advisable as this information could be sensitive.

Could we do something like using use the the domain from the `SS_BASE_URL` or [`Director::host()`](https://github.com/silverstripe/silverstripe-framework/blob/fc2160fa3a7162bb3e296e5d88378cdf6b463fe1/src/Control/Director.php#L539)?

**Comment by GuySartorelli** [comment]
related: silverstripe/silverstripe-cms#2412

**Comment by emteknetnz** [comment]
Using 4.7.x-dev and swiftmailer 5 (where you could still use the `mail()` function)

**/etc/php/7.4/apache2/php.ini**
sendmail_path = /home/www-data/go/bin/mhsendmail -t

**myemail.yml**
```yml
---
Name: myemail
After:
  - '#project-emailconfig'
---
SilverStripe\Core\Injector\Injector:
  Swift_Transport:
    class: Swift_MailTransport
    # class: Swift_SendmailTransport
    # constructor:
    #   0: '/home/www-data/go/bin/mhsendmail -t'
# SilverStripe\Control\Email\Email:
#   admin_email:
#     admin-email@bugfix.test: 'Admin-email'
```

Following email header show up in mailhog:

```
Content-Type: multipart/alternative; boundary="_=_swift_v4_1645065101_44ea918f4d1bea00d5e288cfa08b8132_=_"
Date: Thu, 17 Feb 2022 15:31:41 +1300
From: 
MIME-Version: 1.0
Message-ID: <7f894e091b21c063582db43208797bc0@bugfix7.test>
Received: from localhost by mailhog.example (MailHog)

          id _-Q7AkbYMh5jVPHlXF7eQsLlST6mZLnLVa_kYtTUhlQ=@mailhog.example; Thu, 17 Feb 2022 15:31:41 +1300
Return-Path: <www-data@www>
Subject: Your password reset link
To: steve@silverstripe.com
```
