### ISSUE TITLE
i18nTextCollector produces corrupt output / namespaces when running under PHP8.0

### ISSUE THREAD

**Issue by bimthebam** [silverstripe/silverstripe-framework#10227]
## Affected Version

silverstripe/framework 4.10

## Description

#9665 has introduced PHP8 support - especially for the new PHP parser tokens (`T_NAME_FULLY_QUALIFIED ` and `T_NAME_QUALIFIED`) - but is broken when collecting text from classes which are having `use` statements and even name-spaced method calls.

## Steps to Reproduce

1. Create a simple class which calls the `_t` function, has `use` statements and makes some name-spaced method calls. e.g.

```php
<?php

namespace App\Model;

use SilverStripe\ORM\DataObject;

/**
 * Class TestModelWithTFunctionCalls
 * @package App\Model
 */
class TestModelWithTFunctionCalls extends DataObject
{
    private static $table_name = 'TestModelWithTFunctionCalls';

    public function fieldLabels($includeRelations = true)
    {
        $labels = parent::fieldLabels(true);

        $currentLocale = \SilverStripe\i18n\i18n::get_locale();

        $labels['Test'] = _t(__CLASS__ . '.TEST', 'Test');

        try {

        } catch (\Exception $e) {

        }

        return $labels;
    }
}
```

2. Run the i18nTextCollector task.

As the class resists within the app directory:

```shell
vendor/bin/sake dev/tasks/i18nTextCollectorTask module=app locale=de
```

3. View the generated language file (`app/lang/de.yml`)

### Actual result

Mind the generated namespace (`App\Model\SilverStripe\ORM\DataObject\TestModelWithTFunctionCalls\\SilverStripe\i18n\i18n\get_locale`)

```yml
de:
  App\Model\SilverStripe\ORM\DataObject\TestModelWithTFunctionCalls\\SilverStripe\i18n\i18n\get_locale:
    TEST: Test
  App\Model\TestModelWithTFunctionCalls:
    PLURALNAME: 'Test Model With T Function Callss'
    PLURALS:
      one: 'A Test Model With T Function Calls'
      other: '{count} Test Model With T Function Callss'
    SINGULARNAME: 'Test Model With T Function Calls'
```

### Expected result

```yml
de:
  App\Model\TestModelWithTFunctionCalls:
    PLURALNAME: 'Test Model With T Function Callss'
    PLURALS:
      one: 'A Test Model With T Function Calls'
      other: '{count} Test Model With T Function Callss'
    SINGULARNAME: 'Test Model With T Function Calls'
    TEST: Test
```
