### ISSUE TITLE
Show all failed password criteria when changing a password to a not-strong-enough value

### ISSUE THREAD

**Issue by andrewandante** [silverstripe/silverstripe-framework#10270]
## Affected Version

4.10

## Description

I've just added a robust password policy to my site (yay me). When I attempt to set my password to "test" I am warned that:

`Please increase password strength by adding some of the following characters: uppercase, digits, punctuation`

which is fine, but then when I do I get:

`Password is too short, it must be 10 or more characters long`

which is super annoying. It would be much better to flag all the password failures at once, please.

## Steps to Reproduce

Add the following password requirements via yaml:

```yml
---
Name: app-passwords
After: '#corepasswords'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\PasswordValidator:
    properties:
      MinLength: 10
      MinTestScore: 3
```
Then attempt to set a password of "test", followed by a password of "Test1!"

## PR

- [ ] https://github.com/silverstripe/silverstripe-framework/pull/10966
