### ISSUE TITLE
Configuration: `Swift_Transport_NullTransport` requires `Swift_Events_SimpleEventDispatcher` argument

### ISSUE THREAD

**Issue by strarsis** [silverstripe/silverstripe-framework#10603]
## Affected Version
SilverStripe version `4.11.15`.

## Description
Configuration (using the usual `_config/*.yml` approach) for using the `Swift_Transport_NullTransport` in development should work correctly.
But `Swift_Transport_NullTransport` requires an argument of type `Swift_Events_SimpleEventDispatcher`.

## Steps to Reproduce
1. Create a new configuration file for using `Swift_Transport_NullTransport` on development, e.g. `_config/maildev.yml`, [as described in the SilverStripe 4.x Email docs](https://docs.silverstripe.org/en/4/developer_guides/email/#mailer-configuration-for-dev-environments):
```yml
---
Name: mydevemailconfig
After:
  - '#emailconfig'
Only:
  environment: dev
---

SilverStripe\Core\Injector\Injector:
  Swift_Transport:
    class: Swift_Transport_NullTransport
````
2. Ensure the development (`dev`) environment is set for the site.
3. Make the site use the mailer, notice that a PHP fatal error occurs, as the `Swift_Transport_NullTransport` constructor requires an argument of type `Swift_Events_SimpleEventDispatcher`.
4. There is no documented or programmable way for passing an existing or new `Swift_Events_SimpleEventDispatcher` to `Swift_Transport_NullTransport` in the configuration yml. The code listing in the documentation is incomplete and no mechanism is mentioned for passing actual PHP code or classes to be constructed to injected class constructor.
This configuration for example passes `new Swift_Events_SimpleEventDispatcher()` as literal string to the `Swift_Transport_NullTransport` constructor:
```yml
SilverStripe\Core\Injector\Injector:
  Swift_Transport:
    class: Swift_Transport_NullTransport
    constructor:
      0: 'new Swift_Events_SimpleEventDispatcher()'
````

I had to use `Swift_SendmailTransport` sample from the docs instead with the [`catchmail` binary as argument](https://docs.silverstripe.org/en/4/developer_guides/email/#mailer-configuration-for-dev-environments:~:text=If%20you%27re%20using-,MailCatcher,-%2C%20or%20a%20similar) (which is possible, as it is a string) in the configuration yml instead.  This then behaves basically lik the `Swift_Transport_NullTransport`.

**Comment by GuySartorelli** [comment]
I think the class you probably want to use is `Swift_NullTransport` which [doesn't require any constructor arguments](https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/NullTransport.php)

If for some reason you did need to use `Swift_Transport_NullTransport` you can _inject_ an instance of `Swift_Events_SimpleEventDispatcher` like so:
```yml
SilverStripe\Core\Injector\Injector:
  Swift_Transport:
    class: Swift_Transport_NullTransport
    constructor:
      - '%$Swift_Events_SimpleEventDispatcher'
```

That syntax is documented here: https://docs.silverstripe.org/en/4/developer_guides/extending/injector/#special-yml-syntax though I admit the documentation could be a tad more verbose.
