### ISSUE TITLE
setting mailer DSN string using environment variable doesn't work.

### ISSUE THREAD

**Issue by guyvanbael** [silverstripe/silverstripe-framework#10741]
## Affected Version: Silverstripe 5

If you set a custom dsn string like this (as stated in the v5 docs)
MAILER_DSN=“sendmail://default?command=/usr/local/bin/mhsendmail%20-t”
It generates this error:
[Emergency] Uncaught Symfony\Component\Mailer\Exception\TransportException: Connection to “process /usr/sbin/sendmail -bs” has been closed unexpectedly.

Seems like its not using the custom binary, but the default one.
If you set it using yml, then it's using ther custom one.

**Comment by emteknetnz** [comment]
In case anyone else looking at this is wondering, `/usr/sbin/sendmail -bs` is what symfony/mailer will default to if no other configuration is present - https://github.com/symfony/mailer/blob/6.2/Transport/SendmailTransport.php#L36

I've always got mailhog running on my docker setup and I'm using the following MAILER_DSN:

`MAILER_DSN="sendmail://default?command=/home/www-data/go/bin/mhsendmail%20-t"`

Which is basically the same as yours, just mailhog is installed in a different location. Email works correctly for me.

@guyvanbael
- Can you just confirm your mailhog binary is definitely installed at `/usr/local/bin/mhsendmail` ?
- Also can you please confirm if your .env is using `“` as in your original description or regular double quotes `"`

**Comment by guyvanbael** [comment]
@emteknetnz 
This is my dockerfile (it's based of off Brett Taskers one)

```dockerfile
FROM brettt89/silverstripe-web:8.1
RUN curl -LkSso /usr/bin/mhsendmail 'https://github.com/evertiro/mhsendmail/releases/download/v0.2.0-M1/mhsendmail_linux_arm64'&& \
    chmod 0755 /usr/bin/mhsendmail && \
    echo 'sendmail_path = "/usr/bin/mhsendmail --smtp-addr=mailhog:1025"' > /usr/local/etc/php/php.ini;
# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
```

This my docker-compose file

```yml
version: "3.8"
services:
  silverstripe:
    image: ss81mailhog
    ports:
       - 8080:80
    volumes:
       - .:/var/www/html
       - ./silverstripe.ini:/usr/local/etc/php/conf.d/silverstripe.ini
    depends_on:
       - database
    environment:
       - DOCUMENT_ROOT=/var/www/html
       - SS_TRUSTED_PROXY_IPS=*
       - SS_ENVIRONMENT_TYPE=dev
       - SS_DATABASE_SERVER=database
       - SS_DATABASE_NAME=testss5beta
       - SS_DATABASE_USERNAME=root
       - SS_DATABASE_PASSWORD=
       - SS_DEFAULT_ADMIN_USERNAME=admin
       - SS_DEFAULT_ADMIN_PASSWORD=admin
       - SS_ERROR_LOG=debug.log
       - MAILER_DSN="smtp://mailhog:1025"
  database:
    image: arm64v8/mysql:8.0.32
    environment:
       - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
       - ./db-data:/var/lib/mysql
  phpmyadmin:
   image: arm64v8/phpmyadmin
   ports:
     - 9191:80
   environment:
     - MYSQL_USERNAME=root
     - MYSQL_ROOT_PASSWORD=
     - PMA_HOST=database
     - UPLOAD_LIMIT=1G
  mailhog:
   image: jcalonso/mailhog
   ports:
     - "1025:1025"
     - "8025:8025"
```

and this is my yml-config for mailer

```yml
---
Name: mailer-project
After: 'mailer'
---
SilverStripe\Core\Injector\Injector:
  Symfony\Component\Mailer\Transport\TransportInterface:
    constructor:
      dsn: '`MAILER_DSN`'
```
