### ISSUE TITLE
ImageBackend 'auto' driver

### ISSUE THREAD

**Issue by lekoala** [silverstripe/silverstripe-framework#11186]
### Description

So this is not the first time someone uploaded a crazy large image (not in terms of mb, but in terms of pixel) and that gd fails.
It's not really convenient to set the driver according to the environment. My wish would be that there would be a 'auto' setting picking gd or imagick if the extension is loaded as a new config flag for InterventionBackend

It's easy to do it in userland like this:

```php
<?php

namespace App\Common;

use SilverStripe\Assets\InterventionBackend as AssetsInterventionBackend;
use Intervention\Image\ImageManager;

class InterventionBackend extends AssetsInterventionBackend
{

    /**
     * @return ImageManager
     */
    public function getImageManager()
    {
        $manager = parent::getImageManager();
        if (extension_loaded('imagick')) {
            $manager->configure([
                'driver' => 'imagick'
            ]);
        }
        return $manager;
    }
}
```

```yml
---
Name: myassetsimage
After: '#assetsimage'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Assets\Image_Backend:
    class: App\Common\InterventionBackend
    factory: '%$SilverStripe\Assets\ImageBackendFactory'
```

but I guess i'm not the only one having this issue :-)

### Validations

- [X] You intend to implement the feature yourself
- [X] You have read the [contributing guide](https://docs.silverstripe.org/en/contributing/code/)
- [X] You strongly believe this feature should be in core, rather than being its own community module
- [X] You have checked for existing issues or pull requests related to this feature (and didn't find any)

**Comment by lozcalver** [comment]
Just a thought for your specific issue (different config per environment) - of course the best defence for this is to ensure that your dev/test environments mimic production as closely as possible. That said, would this work for you?

```yml
---
Only:
  classexists: 'Imagick'
---
SilverStripe\Core\Injector\Injector:
  Intervention\Image\ImageManager:
    constructor:
      - { driver: imagick }
```

I’m not against changing framework to default to the “best” option, but I think we’d have to do that in a major release in case people are using an environment with Imagick installed, but specifically want to keep using GD.
