### ISSUE TITLE
Environment Variables in Injector only work in some circumstances

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-framework#11571]
### Module version(s) affected

5.2.22

### Description

It's possible to specify environment variables in injector constructor properties in yml configs.
Let's assume we have a environment variable named `SS_BASE_URL=http://example.com`. The following example will pass the string `http://example.com` as first argument to the constructor of Foobar:
```
SilverStripe\Core\Injector\Injector:
  Foobar:
    constructor:
      - '`SS_BASE_URL`'
```
However, this only works, if the string starts and ends with a `` ` ``
This means:

- ``'`SS_BASE_URL`'`` works
- ``'`SS_BASE_URL` test'`` does NOT work
- ``'`SS_BASE_URL` test `SS_BASE_URL`'`` works
- ``'`SS_BASE_URL` test `SS_BASE_URL` test'`` does NOT work
- ``'`SS_BASE_URL` test `'`` works

### How to reproduce

Real usecase: 
I wish to add the base url to the subject line when using the MailHandler for error logging. However, the following example will not replace SS_BASE_URL with the expected value from .env

```yml
---
Name: app-logging
---
SilverStripe\Core\Injector\Injector:
  Psr\Log\LoggerInterface:
    calls:
      MailHandler: [ pushHandler, [ '%$MailHandler' ] ]
  MailHandler:
    class: Monolog\Handler\NativeMailerHandler
    constructor:
      - errors@example.com
      - '`SS_BASE_URL` %message%'
      - errors@example.com
      - error
    properties:
      ContentType: text/html
      Formatter: '%$SilverStripe\Logging\DetailedErrorFormatter'
```

### Possible Solution

In ``Injector`` Line 529 we are checking if the string starts and ends with a `` ` `` (via regex ``'/^`.+`$/'``).   
We should instead only check if it contains two `` ` `` with content inside (``'/`.+`/'``)

https://github.com/silverstripe/silverstripe-framework/blob/620c1b04699daa1d306de130dbecd1f1a92583fc/src/Core/Injector/Injector.php#L529

### Validations

- [x] Check that there isn't already an issue that reports the same bug
- [x] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)
