### ISSUE TITLE
Support for removing Director:rules from yaml.

### ISSUE THREAD

**Issue by n8-dev** [silverstripe/silverstripe-framework#11757]
### Description

Say you have a module (otherwise any code that you can not change) that has the following

```yaml
---
Name: foo
After: 'otherFoo'
---
SilverStripe\Control\Director:
  rules:
    fizz: Namespace\Of\PageController
```

These details feed into `SiteTree::getExcludedURLSegements()` which ultimately block CMS created pages from occupying these paths.

There is no current way to nullify, or remove this via yaml.

Extensions allow doing this via a `false`

So something like this doing the same would be nice.

```yaml
---
Name: myfoo
After: 'foo'
---
SilverStripe\Control\Director:
  rules:
    fizz: false
```

And then that `fizz` on `rules` would no longer exist.

### Additional context or points of discussion

Yes currently I have the ability to get what I need via the hook `updateExcludedURLSegments()`

Other things can be `nulled` like the `extensions` array (when a key is used)

(Also noting we don't have a term for this idea... around the ability to "Nullify existing yaml configs, hency any awkward naming on this.)

I guess there is a greater topic/issue here, general ability to support nullifying things...

### Validations

- [x] You intend to implement the feature yourself
- [x] You have read the [contributing guide](https://docs.silverstripe.org/en/contributing/code/)
- [x] You strongly believe this feature should be in core, rather than being its own community module
- [x] You have checked for existing issues or pull requests related to this feature (and didn't find any)
