### ISSUE TITLE
[2010-11-10] SapphireTest: Throw error in YML fixture when trying to use a has_many as many_many relationship

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1925]
created by: @chillu (ischommer)
assigned to: @chillu (ischommer)
created at: 2010-11-10
original ticket: http://open.silverstripe.org/ticket/6184

---

If you assign the has_one side of a has_many to more than one object (treating it as many_many), the last assignment will win. Given that the created DB is typically not inspected, this can lead to long debugging sessions. Its a particular problem when parts of the YML are just copypasted.

Demo code:

```
class Course extends DataObject {
    static $db = array('Title'=>'Text');
    static $has_many = array('CourseOfferings'=>'CourseOffering');
}

class CourseOffering extends DataObject {
    static $db = array('Title'=>'Text');
    static $has_one = array('Course'=>'Course');
}
```

YML

```
CourseOffering:
    offering1:
        Title: Offering 1
Course:
    course1:
        Title: Course 1
        Offerings: =>CourseOffering.offering1
    course2:
        Title: Course 1
        # Overrides the above
        Offerings: =>CourseOffering.offering1
```
