### ISSUE TITLE
allowed actions not working in extension...

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#2643]
Have a look at these two files.

_config.yml

``` yml
DevelopmentAdmin:
  extensions:
    - EcommerceDevelopmentAdminDecorator
  allowed_actions:
    - 'ecommerce'

```

EcommerceDevelopmentAdminDecorator.php: 

``` php
class EcommerceDevelopmentAdminDecorator extends Extension{

    /**
     * @param SS_HTTPRequest
     * @return HTML
     **/
    function ecommerce(SS_HTTPRequest $request) {
        return EcommerceDatabaseAdmin::create();
    }

}
```

when I go to /ecommerce/dev/  I get:

Action 'ecommerce' isn't allowed on class DevelopmentAdmin.

When I add a method to DevelopmentAdmin "ecommerce" then it works.  However - when I add "ecommerce" to DevelopmentAdmin::allowed_actions i keep getting: Action 'ecommerce' isn't allowed on class DevelopmentAdmin.
