### ISSUE TITLE
BUG yaml Only and Except rules fail to detect environment

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#3041]
Since most of the time the environment is set via _ss_environment.php, which isn't executed until after the manifest has been generated.

Test cases do test explicitly setting the environment and checking the behaviour of these rules, this doesn't reflect the order that the manifest and environment are checked in practise.

Testing setting Director.enviroment_type via config also fails.

Test scenario:

in _ss_environment.php

``` php
define('SS_ENVIRONMENT_TYPE', 'dev');
```

in mysite/_config/config.yml

``` yml

---
Name: defaultprocessor

---
Injector:
  SearchUpdateProcessor:
    class: SearchUpdateImmediateProcessor

---
Name: queuedjobprocessor
Except:
  Environment: dev

---
Injector:
  SearchUpdateProcessor:
    class: SearchUpdateQueuedJobProcessor
```

in mysite/_config.php

``` php
Debug::dump(Config::inst()->get('Injector', 'SearchUpdateProcessor'));
```

The result is output `SearchUpdateQueuedJobProcessor`
