### ISSUE TITLE
belongs_many_many relations could not be translated

### ISSUE THREAD

**Issue by g4b0** [silverstripe/silverstripe-framework#3581]
example:

``` yaml
  DoIngredient:
    PLURALNAME: Ingredienti
    SINGULARNAME: Ingrediente
    db_Name: Nome
    belongs_many_many_Recipes: Ricette
```

Recipes is still displayed in English
