### ISSUE TITLE
Unable to use CURLOPT_* constants in RestfulService YML configuration.

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-framework#4089]
Right now you cannot specify the standard curl configuration options (e.g. `CURLOPT_CONNECTTIMEOUT`) in the YML configuration. Instead, if you need to change the connect timeout, you'd have to provide the following configuration with the actual value of the constant itself, e.g.:

```yaml
RestfulService:
  default_curl_options:
    78: 10
```

I'd like to be able to do the following instead:

```yaml
RestfulService:
  default_curl_options:
    CURLOPT_CONNECTTIMEOUT: 10
```

I can submit a pull request demonstrating the code that I've written to address this.
