### ISSUE TITLE
Injector factories should be passed the full service definition

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#4442]
Injector factories could be more flexible if they were passed the full service definition as a 3rd argument.

For example, we could use a custom factory to do some special processing on selected `properties`. This relates to my work on #4430

 * Advantage: Factories can be used to tidy up confusing aspects of Injector service definition
 * Disadvantage: Factories could do anything, risking that we get a more divergent & confusing set of configuration approaches. We may end up with service definitions that have options other than `class`, `constructor`, `properties`, and `dependencies`.

One way to mitigate that disadvantage would be to set some guidelines for writing good factories.

The change would be trivial and I'll post a PR if I get buy-in, but I want to run it past people first.

**Comment by sminnee** [comment]
Note: the specific use-case that I want is that I want to grab the `properties.Handler` argument, do some processing, and pass its contents as repeated calls to `Logger::pushHandler()`. In doing this, my hope is that same configuration approach can be maintained even if Monolog improves things in the future to mitigate the need for a custom factory.

An alternative approach to this would be to shift the handling of the `properties` and `dependencies` argument to become part of the factory. Since it all relates to instantiation & set-up of the object, I don't see why that would be *wrong*, but others may disagree.

@nyeholt since you wrote the original class, it would be good to get your feedback.

**Comment by sminnee** [comment]
@stevie-mayhew you may have views on this.

**Comment by sminnee** [comment]
A related issue that came up discussing logger was the ability to inline service definitions within properties.

Right now, to create a handler with a custom formatter, two service definitions are necessary:

    Injector:
      DisplayErrorHandler:
        class: SilverStripe\Framework\Logging\HTTPOutputHandler
        constructor:
          - "notice"
        properties:
          Formatter: %$DisplayErrorFormatter
      DisplayErrorFormatter:
        class: SilverStripe\Framework\Logging\DetailedErrorFormatter

It would be nicer if a service definition could be inlined:

    Injector:
      DisplayErrorHandler:
        class: SilverStripe\Framework\Logging\HTTPOutputHandler
        constructor:
          - "notice"
        properties:
          Formatter:
            class: SilverStripe\Framework\Logging\DetailedErrorFormatter

However, this gets a little bit "magic": you have to know that an map containing a class key should be interpreted as a service definition. It would be nicer if there was a mechanism for indicating an inlined service definition. I'm not sure what that should be, though.

To be flexible, I would say that service definitions should be able to be inlined wherever a service definition reference can currently be used:

 * constructor arguments
 * properties
 * array elements within either other those

In the absence of core changes, it will be possible to create custom factories that implement this in specific cases. It would also be possible to create an `InlinedServiceDefinitionFactory` that would scan any `constructor` and `properties` references and process the inlined service definition.

It would be easier to do this nicely if the processing of constructor and properties was shifted to be a responsibility of the factory: that is, the factory becomes fully responsible for processing a service configuration.

You could have this, which strictly speaking, would be a factory-factory, which I can't quite believe I am advocating.

    $factory = isset($spec['factory']) ? $this->get($spec['factory']) : $this->getObjectCreator();
    $factory->createFactoryForService($spec)->create();

Or we could have this, which is closer to what we currently have. It's a little arbitrary that class & params are broken out separately.

    $factory = isset($spec['factory']) ? $this->get($spec['factory']) : $this->getObjectCreator();
    $factory->create($class, $params, $spec);

The mixing in of constructor arguments is also a little arbitrary: strictly speaking, constructor arguments should be arguments to the factory, rather than being bound directly to the constructor arguments of the underlying object. The factory-factory makes it easier to do something like this:

    $factory = isset($spec['factory']) ? $this->get($spec['factory']) : $this->getObjectCreator();
    $factory->createFactoryForService($spec)->create($constructorParams);

**Comment by nyeholt** [comment]
(looks like you got your post in a few seconds before I could get my reply in!) 

Just bringing across a couple of points from #4430 - 

- I would like to improve some of the way properties are resolved so that, for example, a property could be another service definition that the injector would subsequently bootstrap, or retrieved from the environment, or x or y or z rather than the hardcoded scalar value or %$ lookup as current

- Sam disliked having to create a separate Formatter service definition just to map it as a property of the handler service definition (global namespace pollution, additional entities for a developer to know about)

Generally speaking I agree with your points regarding the need to define additional global entities just for them to be referenced in the one place. My concern around it is related to not being able to subsequently redefine the configuration of those internally defined objects, but at that point you can always override the definition of the top level object. I guess the test of what would be appropriate is whether the inner object would be constantly overridden. What I mean is (pseudo config only)

```yml

Injector
  EmailLogWriter:
    class: \Some\Namespace\EmailLogWriter
    properties:
      to: me@example.com
      subject: There was an error on your test site
  FileLogWriter:
    class: \Some\Namespace\FileLogWriter
    properties:
      filename: /file/system/path/output.log
  Logger:
    class: \Some\Other\Namespace\Logger
    properties:
      handlers:
        - %$EmailLogWriter
        - %$FileLogWriter
```

versus

```yml

Injector:
  Logger:
    class: \Some\Other\Namespace\Logger
    properties:
      handlers:
        0:
          resolve: true
          id: EmailLogWriter
          class: \Some\Namespace\EmailLogWriter
          properties:
            to: me@example.com
            subject: There was an error on your test site
        1: 
          resolve: true
          id: FileLogWriter
          class: \Some\Namespace\FileLogWriter
          properties:
            filename: /file/system/path/output.log
```

In this scenario both log writers could/would be re-configured by end users - which provides more clarity?

Either way - I think the concept of adding a proper property resolver layer has merit - I'm not sure yet what the performance impact would be though. 


Also - just because FactoryFactory :+1: x :100:
