### ISSUE TITLE
REGRESSION: Hi [user] and logout button in CMS mis-aligned (3.x-dev)

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#4541]
![](https://dl.dropboxusercontent.com/u/3429338/Clippings/2015-08/2015-08-25_17-43-04-QCfbnBDEXM.png)

**Comment by chillu** [comment]
@scott1702 @clarkepaul

**Comment by scott1702** [comment]
@dhensby What browser? I can't seem to replicate.

**Comment by dhensby** [comment]
@scott1702 chrome win10 x64

**Comment by dhensby** [comment]
I can confirm I just replicated this with a brand new install using:

composer create-project silverstripe/installer /path/to/webroot 3.x-dev

**Comment by dhensby** [comment]
CSSrule responsible for being out of line:

```css
.cms-login-status span {
    padding-top: 6px
}
```

CSS rule for being too much padding around it:

```css
.cms-login-status {
    padding: 12px 0; /* needs to be less (8px is good) */
    min-height: 28px; /* needs to be removed */
    ...
}
```
