### ISSUE TITLE
[3.2] There are no way to connect to different databases with DB::connect()

### ISSUE THREAD

**Issue by gregsmirnov** [silverstripe/silverstripe-framework#4735]
The reason is that Injector builds all databases with shared connector.

So, for MySQLDatabase there is just one shared service MySQLiConnector.
```
$dbA = DB::connect($dbAconfig, 'default');
$dbB = DB::connect($dbBconfig, 'alt');
```
$dbB is actually connected to the server A.

**Comment by tractorcow** [comment]
Hm, I think you can alter the behaviour of injector in config.

```yaml
Injector:
  PDOConnector:
    class: PDOConnector
    type: prototype
```

Should force all objects that depend on PDOConnector to require a separate instance for each connection.
