### ISSUE TITLE
Config moduleexists, classexists etc don’t support multiple values

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#4820]
You can’t do stuff like:

```yml
---
Name: foo
Only:
  moduleexists:
    - modulea
    - moduleb
---
Foo: bar
```

Admittedly there’s some ambiguity over whether this would be an “and” or an “or”, but I don’t think we could realistically support both (not without introducing some obscure syntax). I don’t think we need to support an “or” anyway as you could just do two blocks instead, so it’s probably more of a documentation issue.

**Comment by kinglozzer** [comment]
Closing this because it’s a feature request

**Comment by tractorcow** [comment]
@kinglozzer this works:

```yaml
Only:
  moduleExists: modulea
  moduleEXISTS: moduleb
  MODULEEXISTS: module3
```

Because case sensitivity.
