### ISSUE TITLE
Proposed: Facebook oEmbed Support

### ISSUE THREAD

**Issue by UndefinedOffset** [silverstripe/silverstripe-framework#5066]
Looks like Facebook finally got around to adding support for oEmbed to their platform, however looks like auto discover does not work. Should support be added to the core oEmbed providers list? Looks like they have two different end-points for the most part https://developers.facebook.com/docs/plugins/oembed-endpoints. My initial pass at them seems to have resulted in the following configuration. It's allot but I think it's the simplest it can be given the url's they support and don't support?

```yml
Oembed:
  providers:
    "http://www.facebook.com/*/posts/*":
      https: "https://www.facebook.com/plugins/post/oembed.json/"
    "http://www.facebook.com/*/activity/*":
      https: "https://www.facebook.com/plugins/post/oembed.json/"
    "http://www.facebook.com/*/posts/*":
      https: "https://www.facebook.com/plugins/post/oembed.json/"
    "http://www.facebook.com/*/photos/*":
      https: "https://www.facebook.com/plugins/post/oembed.json/"
    "http://www.facebook.com/*/media/*":
      https: "https://www.facebook.com/plugins/post/oembed.json/"
    "http://www.facebook.com/*/questions/*":
      https: "https://www.facebook.com/plugins/post/oembed.json/"
    "http://www.facebook.com/notes/*":
      https: "https://www.facebook.com/plugins/post/oembed.json/"
    "http://www.facebook.com/photo.php?fbid=*":
      https: "https://www.facebook.com/plugins/post/oembed.json/"
    "http://www.facebook.com/permalink.php?story_fbid=*":
      https: "https://www.facebook.com/plugins/post/oembed.json/"
    "http://www.facebook.com/*/videos/*":
      https: "https://www.facebook.com/plugins/video/oembed.json/"
    "http://www.facebook.com/video.php?id=*":
      https: "https://www.facebook.com/plugins/video/oembed.json/"
    "http://www.facebook.com/video.php?v=*":
      https: "https://www.facebook.com/plugins/video/oembed.json/"
```

Technically you could get away with the below but url's that are not supported just fail with a 100x100 object being returned which results in just a link being displayed.

```yml
---
Name: mysite_oembed
After: framework#Oembed
---
Oembed:
  providers:
    "http://www.facebook.com/*/videos/*":
      https: "https://www.facebook.com/plugins/video/oembed.json/"
    "http://www.facebook.com/video.php?id=*":
      https: "https://www.facebook.com/plugins/video/oembed.json/"
    "http://www.facebook.com/video.php?v=*":
      https: "https://www.facebook.com/plugins/video/oembed.json/"
    "http://www.facebook.com/*":
      https: "https://www.facebook.com/plugins/post/oembed.json/"
```
