### ISSUE TITLE
replaceFile not considered by Upload.php

### ISSUE THREAD

**Issue by g4b0** [silverstripe/silverstripe-framework#5137]
SS 3.1.18
Upload class always overwrite files, also if replaceFile is set to false. 
Changing https://github.com/silverstripe/silverstripe-framework/blob/3.1.18/filesystem/Upload.php#L161 to the code below works as expected.

```php
if (true){
```

Following my config
```yaml
---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'mysite'    
# replace files instead of versioning
Upload:
  replaceFile: false
# show an overwrite warning
UploadField:
  defaultConfig:
    overwriteWarning: true
```

Following my upload field
```php
$fields->addFieldToTab(
    'Root.Main', $uploadField = new UploadField(
    'FilePercorso', 'File del percorso'
    )
);
$uploadField->setFolderName('Uploads/Percorsi');
$uploadField->setAllowedExtensions(array('gpx'));
```
