### ISSUE TITLE
FileField hidden

### ISSUE THREAD

**Issue by frankmullenger** [silverstripe/silverstripe-framework#5596]
FileFields, such as the one used on the "Import" form for ModelAdmin, are not displayed, it looks like they have opacity set to 0 by this bootstrap rule in node_modules/bootstrap/scss/_custom_forms.scss:
```scss
.file input {
  min-width: 14rem;
  margin: 0;
  filter: alpha(opacity = 0);
  opacity: 0;
}
```
