### ISSUE TITLE
Hardcoded /admin/ url segment for my profile 

### ISSUE THREAD

**Issue by mattrayner** [silverstripe/silverstripe-framework#5680]
I've discovered a bug in `LeftAndMain_MenuStatus.ss` - if you are using a custom admin URL the myprofile link doesn't work.

i.e. with a config like this:

```yaml
Director:
  rules:
    'admin': ''
    'my_custom_admin': 'AdminRootController'
AdminRootController:
  url_base: 'my_custom_admin'
LeftAndMain:
  url_base: 'my_custom_admin'
  url_segment: 'my_custom_admin'
```

The expected my profile url would be `{$AbsoluteBaseURL}my_cusom_admin/myprofile` but is hard coded on line 6:

```
<a href="{$AbsoluteBaseURL}admin/myprofile" class="profile-link">
```

I'm not sure if this helps but on the controller level I'd use something like:
```php
Config::inst()->get('AdminRootController', 'url_base')
```
