### ISSUE TITLE
Adding javascript to LeftAndMain not working as per documentation

### ISSUE THREAD

**Issue by SteveAzz** [silverstripe/silverstripe-framework#6123]
I wanted to add some custom javascript and css to the admin, I took a look at the LeftAndMain class I fond this in  the doc block of `$extra_requirements_javascript`

```
 YAML configuration example:
 <code>
 LeftAndMain:
   extra_requirements_javascript:
     mysite/javascript/myscript.js:
 </code>
```

When I tried the following in an new `config.yml`
```
LeftAndMain:
  extra_requirements_javascript:
    mysite/modules/editor/code/javascript/no-follow.js:
  extra_requirements_css:
    mysite/modules/editor/code/css/no-follow.css:
```

It does not load the javascript file, it only loads the css file, but when I do the following, it works, is there a possible issue? or just outdated documentation?
```
LeftAndMain:
  extra_requirements_css:
    - mysite/modules/editor/code/css/no-follow.css
  extra_requirements_javascript:
    - mysite/modules/editor/code/javascript/no-follow.js
```
