### ISSUE TITLE
Namespace imports in config.yml files

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#6596]
With the upgrade to 4 comes with it the adoption of namespaces (yay).

In PHP files you can "import" classes with the `use` keyword and then refer to the classes with their shorter class name.

However, this is not possible in the yaml files, all classes must be their <abbr title="Fully Qualified Class Name">FQCN</abbr>. This leads to very noisy yaml files that could benefit in much the same way PHP files do from importing FQCNs.

**Comment by robbieaverill** [comment]
Definitely +1 for me, this is especially obvious in test fixtures

**Comment by sminnee** [comment]
Would you do this in the preamble section, with `name`, `only`, etc?

```yml
---
name: myconfig
mappings:
  SiteTree: SilverStripe\CMS\Models\SiteTree
  AppModels: Me\MyApp\Models
---
Injector:
  SiteTree:
    class: AppModels\CustomSiteTree
```

It could be handled as a search/replace on any values, replacing `/^SearchKey$|\\/`.
