### ISSUE TITLE
Simplify dynamic cache creation

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#6711]
At the moment it's necessary to add a minimal level of config to create a new cache.

```yaml
---
Name: mycache
---
SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.myCache:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: 'mycache'
```

Created with

```php
$cache = Injector::inst()->get(CacheInterface::class.'.myCache');
```

What we should be able to do is simply

```
$cache = Injector::inst()->get(CacheInterface::class.'.somenewnamespace');
```

And this auto-creates an instance based on a default cache definition.

```yaml
---
name: defaultcache
---
SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface:
    factory: SilverStripe\Core\Cache\CacheFactory
```

This change would be made in Injector, but would be initially useful to cache generation.

If a service is requested for `class.name`, but none is registered, it should fall back to `class` definition if it exists.

CacheFactory::create() would be invoked based on the default configuration, but the full top level cache name is passed into the `$service` argument, which is used to populate the value of `namespace`.

```php
// Get default $namespace constructor args if not declared
list($class, $namespace) = explode('.', $service);
```
