### ISSUE TITLE
TinyMCE not picking up theme editor.css

### ISSUE THREAD

**Issue by andrewandante** [silverstripe/silverstripe-framework#6767]
I have an additional font defined in my theme - `themes/future-imperfect/css/editor.css`. This font is not rendered in the WYSIWYG editor. I believe this is because when we are in the CMS, the method `SSViewer::get_themes()` is used to check for `editor.css` in the themes it finds - however, because we are in the CMS, the method returns only `['silverstripe/framework:/admin/themes/cms-forms', '$default']`, so it never finds my `editor.css` file.

Using framework version `dev-master bba86bb`.

My `config.yml` looks like this:

```yml
SilverStripe\View\SSViewer:
  theme_enabled: true
  themes:
    - 'future-imperfect'
    - '$default'
```
