### ISSUE TITLE
[3.x] Image and Image_Cached classes cannot be substituted with Injector

### ISSUE THREAD

**Issue by gregsmirnov** [silverstripe/silverstripe-framework#6838]
There are many modules that extend core Image class, for example in [kinglozer/silverstripe-tinypng](https://github.com/kinglozzer/silverstripe-tinypng).
Using this configuration:

```yml
Injector:
  Image:
    class: TinyPngImage
  Image_Cached:
    class: TinyPngImage_Cached
```

However `Image::getFormattedImage()` creates `Image_Cached` with **new** operator.

It should be just one line fix for Injector:

```
 - $cached = new Image_Cached($cacheFile);
+ $cached = Injector::inst()->createWithArgs('Image_Cached', array($cacheFile));
```

Another improvement is dynamic tag generation, with API to set/remove any attribute, and IMG tag itself (alternatives - amp-img and picture). This would allow modules to extend Image class in all possible ways.

Would it be possible to add this change in 3.6.0 release?
