### ISSUE TITLE
error in installing beta1

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#7120]
```txt

Fatal error: Uncaught Error: Cannot instantiate interface SilverStripe\Logging\ErrorHandler in /container/application/public/framework/src/Core/Injector/InjectionCreator.php:26 Stack trace: 

#0 /container/application/public/framework/src/Core/Injector/InjectionCreator.php(26): ReflectionClass->newInstance() 

#1 /container/application/public/framework/src/Core/Injector/Injector.php(573): SilverStripe\Core\Injector\InjectionCreator->create('SilverStripe\\Lo...', Array) 

#2 /container/application/public/framework/src/Core/Injector/Injector.php(986): SilverStripe\Core\Injector\Injector->instantiate(Array, 'SilverStripe\\Lo...')

#3 /container/application/public/framework/src/Core/Injector/Injector.php(914): SilverStripe\Core\Injector\Injector->getNamedService('SilverStripe\\Lo...', true, Array) 

#4 /container/application/public/framework/src/Core/CoreKernel.php(515): SilverStripe\Core\Injector\Injector->get('SilverStripe\\Lo...') 

#5 /container/application/public/framework/src/Core/CoreKernel.php(187): SilverStripe\Core\CoreKernel- in /container/application/public/framework/src/Core/Injector/InjectionCreator.php on line 26

```

Error on ....

- all pages
- only via http (not via cli)
- only on server
- deleted DB but that did not help

using the recipe below:

```yml
{
    "name": "silverstripe/installer",
    "description": "The SilverStripe Framework Installer",
    "require": {
        "silverstripe/framework": "4.0.0-beta1",
        "silverstripe/cms": "4.0.0-beta1",

        "silverstripe/reports": "*",
        "silverstripe/siteconfig": "*",
        "silverstripe/campaign-admin": "*",

        "silverstripe/admin": "*",
        "silverstripe/asset-admin": "*",
        "silverstripe/assets": "*",
        "silverstripe/config": "*",
        "silverstripe/versioned": "*",

        "silverstripe/graphql": "*",

        "silverstripe-themes/simple": "~3.2.0",
        "gdmedia/ss-auto-git-ignore": "dev-master"
    },
    "require-dev": {
        "phpunit/PHPUnit": "^5.7",
        "silverstripe/graphql-devtools": "*"
    },
    "extra": {
        "branch-alias": {
            "dev-master": "4.0.x-dev"
        }
    },
    "config": {
        "process-timeout": 600
    },
    "prefer-stable": true,
    "minimum-stability": "dev",
    "scripts": {
        "post-install-cmd": [
            "rm _dev -rf"
        ],
        "post-update-cmd": [
            "GDM\\SSAutoGitIgnore\\UpdateScript::Go"
        ]
    }
}

```
