### ISSUE TITLE
Can not change logo and application link from admin panel

### ISSUE THREAD

**Issue by cansozeri** [silverstripe/silverstripe-framework#7631]
The brand logo and application link can not change because  LeftAndMain::setApplicationName() and other functions is not exists anymore. There is no clear doc for how to do this ???

# PRs

 - [ ] https://github.com/silverstripe/silverstripe-admin/pull/365
 - [ ] https://github.com/silverstripe/silverstripe-framework/pull/7633

**Comment by kinglozzer** [comment]
@cansozeri You’ll need to use the `LeftAndMain.application_name` config setting instead:

```yml
SilverStripe\Admin\LeftAndMain:
  application_name: 'My Website'
  application_link: '//www.mysite.com/'
```

The logo will need to be changed with CSS as before:

```yml
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - mysite/css/mystyles.css
```


`setApplicationName()` and `setApplicationLink()` were marked as deprecated in 3.x, but I don’t see them mentioned in the changelog anywhere so perhaps we should add a note there to make it clear.
