### ISSUE TITLE
smtp e-mail issue

### ISSUE THREAD

**Issue by cansozeri** [silverstripe/silverstripe-framework#7700]
## Affected Version
4.0.0

## Description
I can not send e-mail with mail function with using smtp. I can not produce any error too ? I think there must a debug option. 

I have added settings to config.yml

```yml
SilverStripe\Core\Injector\Injector:
  Swift_Transport:
    class: Swift_SmtpTransport
    properties:
      Host: mail.example.com
      Port: 587
      Encryption: tls
    calls:
      Username: [ setUsername, ['mailadmin@example.com'] ]
      Password: [ setPassword, ['examplepass1'] ]
      AuthMode: [ setAuthMode, ['login'] ]
```

```php
$email = new Email('mailadmin@example.com', $user_email, $subject, $text);
$email->send()
```

I tried to get print out swift mailer transport host and other stuff but I can't. It seems null.

**Comment by tractorcow** [comment]
Not sure what's causing this issue; Someone needs to investigate and determine the cause of this issue.

**Comment by tractorcow** [comment]
Your config above seems correct after checking the Swift_SmtpTransport class.

You may need to debug the executeCommand manually (var_dump everywhere?).

**Comment by dhensby** [comment]
It does work, however you need to make sure you add your configuration into a new file (email.yml) like so:

mysite/_config/email.yml
```yml
---
Name: myproject
After:
  - '#emailconfig'
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: mysite
SilverStripe\Core\Injector\Injector:
  Swift_Transport:
    class: Swift_SmtpTransport
    properties:
      Host: mail.example.com
      Port: 587
      Encryption: tls
    calls:
      Username: [ setUsername, ['mailadmin@example.com'] ]
      Password: [ setPassword, ['examplepass1'] ]
      AuthMode: [ setAuthMode, ['login'] ]
```

When I do this I get the following error:

```
[Emergency] Uncaught Swift_TransportException: Connection could not be established with host mail.example.com [php_network_getaddresses: getaddrinfo failed: Name or service not known #0]
GET /
Line 268 in /vagrant/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php
```

Which feels expected to me

**Comment by dhensby** [comment]
I've added a clarification to the docs regarding this too

**Comment by cansozeri** [comment]
@dhensby Thanx - but nothing changed. mail->send() returns false and there is no error. I have created email.yml and flush. Still it is not working.. It is very sad that I can not get any output why it is broken or why it returned false.. There must be an option that getting output about what is gonna wrong about it.

**Comment by cansozeri** [comment]
in Swift_SmtpTransport class var_dump($host) in __construct method prints nothing. I think it is never loaded. I don't know what to do then :=)

**Comment by dhensby** [comment]
What happens when you debug out `Injector::inst()->get(Mailer::class)`?

If it's not returning a `Swift_SmtpTransport` object then your config isn't right and you're not registering the smtp transport correctly.

**Comment by cansozeri** [comment]
The output is

`object(SilverStripe\Control\Email\SwiftMailer)#718 (1) {
  ["swift":"SilverStripe\Control\Email\SwiftMailer":private]=>
  object(Swift_Mailer)#723 (1) {
    ["_transport":"Swift_Mailer":private]=>
    object(Swift_MailTransport)#714 (3) {
      ["_extraParams":"Swift_Transport_MailTransport":private]=>
      string(4) "-f%s"
      ["_eventDispatcher":"Swift_Transport_MailTransport":private]=>
      object(Swift_Events_SimpleEventDispatcher)#719 (3) {
        ["_eventMap":"Swift_Events_SimpleEventDispatcher":private]=>
        array(5) {
          ["Swift_Events_CommandEvent"]=>
          string(28) "Swift_Events_CommandListener"
          ["Swift_Events_ResponseEvent"]=>
          string(29) "Swift_Events_ResponseListener"
          ["Swift_Events_SendEvent"]=>
          string(25) "Swift_Events_SendListener"
          ["Swift_Events_TransportChangeEvent"]=>
          string(36) "Swift_Events_TransportChangeListener"
          ["Swift_Events_TransportExceptionEvent"]=>
          string(39) "Swift_Events_TransportExceptionListener"
        }
        ["_listeners":"Swift_Events_SimpleEventDispatcher":private]=>
        array(1) {
          [0]=>
          object(SilverStripe\Control\Email\SwiftPlugin)#725 (0) {
          }
        }
        ["_bubbleQueue":"Swift_Events_SimpleEventDispatcher":private]=>
        array(0) {
        }
      }
      ["_invoker":"Swift_Transport_MailTransport":private]=>
      object(Swift_Transport_SimpleMailInvoker)#720 (0) {
      }
    }
  }
}`

**Comment by dhensby** [comment]
yep, so it's using `Swift_MailTransport` and not `Swift_SmtpTransport` so you haven't registered the transport correctly.

I have tested this with 4.x-dev and can confirm it works with the yaml I've provided.

**Comment by cansozeri** [comment]
But I have added email.yml as you have described.. What can I do extra ??

My code is very simple .. 

`$email = new Email('mailadmin@example.com', $user_email, $subject, $text);
$email->send()`

**Comment by dhensby** [comment]
> What can I do extra ??

You'll need to debug your code and find out why the wrong mailer is being created by `Injector`, which is likely a service definition issue (ie: the yml you're using)

**Comment by cansozeri** [comment]
My yml is 
```
---
Name: myemailconfig
After:
  - '#emailconfig'
SilverStripe\Core\Injector\Injector:
  Swift_Transport:
    class: Swift_SmtpTransport
    properties:
      Host: mail.example.com
      Port: 587
      Encryption: null
    calls:
      Username: [ setUsername, ['example@example.com'] ]
      Password: [ setPassword, ['123456'] ]
      AuthMode: [ setAuthMode, ['login'] ]
```
