### ISSUE TITLE
Authenticator title shows escaped &amp; on login screen

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#7769]
Affects 4.x

When adding a second authenticator, the `MemberAuthenticator` title displays `&amp;` instead of an ampersand.

<img width="643" alt="screen shot 2018-01-17 at 14 58 56" src="https://user-images.githubusercontent.com/1655548/35049140-f6a98540-fb96-11e7-95e6-8912e8d9e9e3.png">

Suggested solution: add the following to `MemberLoginForm`

```php
private static $casting = [
    'AuthenticatorName' => 'HTMLFragment'
];
```

# PRs:

 - [ ] https://github.com/silverstripe/silverstripe-framework/pull/7779

**Comment by tractorcow** [comment]
Can you show me the code you used to add the other authenticator?

The existing casting should be respected; Forcing to html text seems risky.

**Comment by tractorcow** [comment]
Actually I just added the default authenticator twice to reproduce. :)

```yaml
SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\Security:
    properties:
      Authenticators:
        copy: '%$SilverStripe\Security\MemberAuthenticator\MemberAuthenticator'
```
