### ISSUE TITLE
RFC Code smell linting in CI

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#7899]
I would recommend that in addition to code style linting (psr-2), we also include more intensive code-smell detection in CI to detect possible errors.

This could be provided by https://github.com/phpstan/phpstan running as a separate test fixture, along with the phpcs checker.

https://medium.com/@ondrejmirtes/phpstan-2939cd0ad0e3

By better automation of detectable errors, we could cut down on peer review time by allowing submitters to see a list of errors quickly without having to wait for a human to review. Quicker review turn around = time to fix things before a human shows up = faster merges. :)

**Comment by robbieaverill** [comment]
How does PHPStan differ from Scrutinizer CI?

**Comment by tractorcow** [comment]
Oh right, I guess it doesn't at all?

In retrospect stick with scrutinizer. :)

**Comment by robbieaverill** [comment]
One difference by the looks of it is that PHPStan would probably be more configurable from our perspective, and having the checks in the Travis matrix would be more obvious when code becomes smelly than with Scrutinizer, which always passes the GitHub status check but just says "5 new issues found" for example

**Comment by dhensby** [comment]
> which always passes the GitHub status check but just says "5 new issues found" for example

We can (and should) make Scrutinizer fail builds under some circumstances - we just haven't set it up

**Comment by robbieaverill** [comment]
I think it's worth reopening this now. I think including phpstan in Travis builds would provide more value to us than Scrutinizer (currently) does. Either way we'd need to tweak Scrutinizer's config or add phpstan in, but something can be done with this issue =)

**Comment by szepeviktor** [comment]
Actually Scrutinizer has a nice UI, PHPStan is a better static analysis tool.

**Comment by szepeviktor** [comment]
FYI This is the PHPStan configuration used in my PR

```yaml
parameters:
    # TODO Raise to 4 or 7
    level: 0
    paths:
        - %currentWorkingDirectory%/src/
    excludes_analyse:
        # 💥 combinatorial explosion 💥 https://github.com/phpstan/phpstan/issues/2171
        - %currentWorkingDirectory%/src/View/SSTemplateParser.php
        # tidy ext.
        - %currentWorkingDirectory%/src/View/Parsers/TidyHTMLCleaner.php
        - %currentWorkingDirectory%/src/Dev/CSSContentParser.php
        # ezyang/htmlpurifier
        - %currentWorkingDirectory%/src/View/Parsers/PurifierHTMLCleaner.php
        # memcached ext.
        - %currentWorkingDirectory%/src/Core/Cache/MemcachedCacheFactory.php
        # symfony/console
        - %currentWorkingDirectory%/src/Dev/Upgrade/UpgradeBootstrap.php
        # Previous SilverStripe versions
        - %currentWorkingDirectory%/src/Dev/Tasks/MigrateFileTask.php
        - %currentWorkingDirectory%/src/Forms/GridField/GridFieldVersionedState.php
        # tinymce_compressor npm package
        - %currentWorkingDirectory%/src/Forms/HTMLEditor/TinyMCEGZIPGenerator.php
    autoload_files:
        - %currentWorkingDirectory%/thirdparty/php-peg/Parser.php
        - %currentWorkingDirectory%/thirdparty/difflib/difflib.php
        - %currentWorkingDirectory%/thirdparty/simpletest/selector.php
        - %currentWorkingDirectory%/thirdparty/simpletest/page.php
    ignoreErrors:
#        # Where is TransactionalDBConnector?
#        - '#^Class SilverStripe\\ORM\\Connect\\TransactionalDBConnector not found\.$#'
```
