### ISSUE TITLE
[Docs] Memcached cache example doesn’t work

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#7934]
https://docs.silverstripe.org/en/4/developer_guides/performance/caching/#adapters currently includes

```yml
---
After:
  - '#corecache'
---
SilverStripe\Core\Injector\Injector:
  MemcachedClient:
    class: 'Memcached'
    calls:
      - [ addServer, [ 'localhost', 11211 ] ]
  SilverStripe\Core\Cache\CacheFactory:
    class: 'SilverStripe\Core\Cache\MemcachedCacheFactory'
    constructor:
      client: '%$MemcachedClient
```

This doesn’t work, because of the way that config merges arrays. The default Injector configuration for `SilverStripe\Core\Cache\CacheFactory` already provides two arguments to the constructor:

```yml
SilverStripe\Core\Injector\Injector:
  SilverStripe\Core\Cache\CacheFactory:
    class: 'SilverStripe\Core\Cache\DefaultCacheFactory'
    constructor:
      args:
        directory: '`TEMP_PATH`'
        version: null
      logger: '%$Psr\Log\LoggerInterface'
```

When these two blocks are merged in config, the `client` argument is appended as a third argument instead of overriding the two existing ones from core config.

## Solution 1
```yml
---
After:
  - '#corecache'
---
SilverStripe\Core\Injector\Injector:
  MemcachedClient:
    class: 'Memcached'
    calls:
      - [ addServer, [ 'localhost', 11211 ] ]
  MemcachedCacheFactory:
    class: 'SilverStripe\Core\Cache\MemcachedCacheFactory'
    constructor:
      client: '%$MemcachedClient'
  SilverStripe\Core\Cache\CacheFactory: '%$MemcachedCacheFactory'
```

## Solution 2 (untested)
```yml
---
Name: cachereset
After:
  - '#corecache'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Core\Cache\CacheFactory:
    constructor: null
---
After:
  - '#cachereset'
---
SilverStripe\Core\Injector\Injector:
  MemcachedClient:
    class: 'Memcached'
    calls:
      - [ addServer, [ 'localhost', 11211 ] ]
  SilverStripe\Core\Cache\CacheFactory:
    class: 'SilverStripe\Core\Cache\MemcachedCacheFactory'
    constructor:
      client: '%$MemcachedClient'
```
