### ISSUE TITLE
Incorporate reading mode in default object cache key

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#8020]
In partial caching, we use `$CurrentReadingMode` and `$CurrentUser.ID` as a default value in the cache key. 

> An additional global key is incorporated in the cache lookup. The default value for this is $CurrentReadingMode, $CurrentUser.ID. This ensures that the current Versioned state and user ID are used. This may be configured by changing the config value of SSViewer.global_key. It is also necessary to flush the template caching when modifying this config, as this key is cached within the template itself.

https://docs.silverstripe.org/en/4/developer_guides/performance/partial_caching/#partial-caching

We don't do this for [object caching](https://docs.silverstripe.org/en/4/developer_guides/performance/caching/) through `CacheFactory`. This makes it far too easy for developers to forget they're caching an object representation tied to the current stage, which has the potential to leak draft content. In SilverStripe 4, the likelyhood of this will be higher, since more objects are versioned, and graphs of objects are more likely to unexpectedly contain versioned records as well.

```yml
SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.myCache:
    factory: SilverStripe\Core\Cache\DefaultCacheFactory
    constructor:
      namespace: "myCache"
```

```php
$cache = Injector::inst()->get(CacheInterface::class . '.myCache');
$myValue = $cache->get('myCacheKey'); // gets myCacheKey + CurrentReadingMode + CurrentUser
```

In order to opt out, you'd use a different cache factory:

```yml
SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.myCache:
    factory: SilverStripe\Core\Cache\CustomCacheFactory
    constructor:
      namespace: "myCache"
```

It's technically a semver violation to introduce this behaviour in the existing `CacheFactory`, but we could recommend using subclasses of it in our docs and upgrading guide. Not too happy with the naming, suggestions welcome.

# PRs:

 - [x] 4.x: https://github.com/silverstripe/silverstripe-versioned/pull/148
- [ ] 4.x https://github.com/silverstripe/silverstripe-framework/pull/8093
- [x] 3.x https://github.com/silverstripe/silverstripe-framework/pull/8095
- [x] 3.x https://github.com/silverstripe/silverstripe-cms/pull/2180
