### ISSUE TITLE
After in yaml files does not do anything in 3.6.5

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#8098]
## Affected Version

Silverstripe 3.6.5

## Description

`After` value in yaml file does not seem to work. 

we have:

dynamiccache/dynamiccache.yml

```yml
---
Name: dynamiccahe
---
A:
  B: x
```
We have another file (alphabetically above dynamiccache.yml).

dynamic_cache_custom/CustomDynamicCache.yml

```yml
---
Name: CustomDynamicCache
After: dynamiccahe
---
A:
  B: y
```

This second file does not override the first page.

The way we tested it was by putting the following in Page::init:

```php
die(Config::inst()->get('A', 'B'));
```
This always showed 'x' and never 'y' unless we moved our custom yml file to mysite (which is alphabetically after the `dynamiccache` folder). 

We have tried the following combinations:

```yml
---
Name: CustomDynamicCache
After: '/dynamiccache'
---
```
AND 

```yml
---
Name: CustomDynamicCache
After: 'dynamiccache'
---
```
AND 

```yml
---
Name: CustomDynamicCache
After: 'dynamiccache/*'
---
```
AND 

```yml
---
Name: CustomDynamicCache
After: '#dynamiccahe'
---
```
AND 

```yml
---
Name: CustomDynamicCache
After: '/dynamiccahe#dynamiccahe'
---
```
AND 

```yml
---
Name: CustomDynamicCache
After: '*'
---
```

We are not sure if this is an issues in SS4.
