### ISSUE TITLE
i18n and translation doc needs updated to account for namespace

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#8138]
A lot of the examples on these two articles need to be updated to account for the fact that our classes are namespaced now.

https://docs.silverstripe.org/en/4/developer_guides/i18n/
https://docs.silverstripe.org/en/4/developer_guides/templates/translations/

# Example of lies we are telling
```ss
<%t Member.WELCOME 'Welcome {name} to {site}' name=$Member.Name site="Foobar.com" %>
```
```php
_t('LeftAndMain.FILESIMAGES','Files & Images');
```
```YAML
en:
  ImageUploader:
    Attach: 'Attach {title}'
  UploadField:
    NOTEADDFILES: 'You can add files once you have saved for the first time.'
```
