### ISSUE TITLE
Can not override FallbackLocale

### ISSUE THREAD

**Issue by jmfederico** [silverstripe/silverstripe-framework#8467]
This is related to #6805 and should be solved if the solution proposed there is executed. But this is a major problem for multilingual sites that do not require english, so I am opening a new issue.

## Affected Version
4.2.1

## Description
When trying to override the fallback locale, one should be able to create a configuration setting like this (for instance to set Spanish as fallback):
```yml
SilverStripe\Core\Injector\Injector:
  Symfony\Component\Translation\TranslatorInterface:
    calls:
      FallbackLocales: [ setFallbackLocales, [['es']]]
```

But, since the setting is an array, instead of overriding, it add the parameters to the original setting, which ends up being:
```php
array:4 [
  0 => "setFallbackLocales"
  1 => array:1 [
    0 => array:1 [
      0 => "en"
    ]
  ]
  2 => "setFallbackLocales"
  3 => array:1 [
    0 => array:1 [
      0 => "es"
    ]
  ]
]
```

Which will then throw an `InvalidArgumentException` exception.

## Steps to Reproduce
On a SilverStripe project, add this to your config.yml file:

```yml
SilverStripe\Core\Injector\Injector:
  Symfony\Component\Translation\TranslatorInterface:
    calls:
      FallbackLocales: [ setFallbackLocales, [['es']]]
```

<hr>

in the meantime, is there any way to override the value of the fallback language?
