### ISSUE TITLE
Default Grid Field needs redesign - probably already happening, just an additional encouragement

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#8498]
## Affected Version

Latest stable version of SS4.

## Description

My colleague keeps telling me that the Word Press Grid Field is more user friendly.  I dont know if that is true, but I feel the grid field could be improved.  I have raised this before and I know work is underway, but I would really love to see it get better sometime soon.  Here are some examples that could be looked at:

![image](https://user-images.githubusercontent.com/167154/47139164-a3c36400-d317-11e8-9ff4-2d0df2cb8bbe.png)

1. title above buttons seems counter intuitive.  Start with title and then add buttons below? 

2. the link existing has never been very clear (i.e. user select something from the list and then has to do a second click to "link" it.).  This could do with a UX rethink. 

3. There is a search button when there are no records.

Here is one with a record:

![image](https://user-images.githubusercontent.com/167154/47139451-5c89a300-d318-11e8-8b1c-036086a8b8f8.png)

1. spacing between elements does not really make sense.  Why the huge space between "add: and the list itself?  It could all be a bit closer together I reckon. 

![image](https://user-images.githubusercontent.com/167154/47139971-99a26500-d319-11e8-9584-0330b6368335.png)

2. looking at the ..., this would make sense if you had three or four options, but when the options are: 
a. EDIT (clicked most of the time)
b. DELETE (hardly ever needed)
then this just creates an additional hassle to edit a record (i.e. you have to click twice to edit the record, with the added disadvantage that it is now easier to accidentally click delete).  Of course you can also just click on the row, but that is not immediately obvious. Why not show the delete only and make it clearer that the user can click anywhere on the row to edit the record. 

![image](https://user-images.githubusercontent.com/167154/47140123-0584cd80-d31a-11e8-9d99-bf9a578bb849.png)

When you are searching for items with many search fields then they get cut off. 

I would also love to see Better Buttons reintroduced as they will make the user experience much better again (e.g. PREVIOUS / NEXT is awesome even though it is hard to implement).

**Comment by robbieaverill** [comment]
The autocompleter component definitely needs some love! Thanks for the suggestions, they all seem sensible. 

cc @clarkepaul @sachajudd

**Comment by clarkepaul** [comment]
I feel like there was another issue which covers the same things, I'll do a quick hunt for it, it should cover the re-ordering of actions and GridField heading as mentioned here.

![image](https://user-images.githubusercontent.com/555033/47531121-25fbeb80-d909-11e8-83fb-c23649071b8b.png)
^ On this one the text "View 1-1 of 1" shouldn't show if there is no heading, this was done a while back so I'm thinking its a regression? I remember going through (@tractorcow you remember us going through this?).

**Comment by clarkepaul** [comment]
Related https://github.com/silverstripe/silverstripe-framework/issues/8254

**Comment by ScopeyNZ** [comment]
Looking good @newleeland . The designs don't make it clear if a removed row actually disappears after an amount of time. Are the removed rows expected to stay (with the "undo" button visible) until the user navigates away?

**Comment by clarkepaul** [comment]
That part of the design is super old @ScopeyNZ although it was never implemented, it would only be visible for around 5 seconds before disappearing. We could incorporate a countdown indicator on the action which other UI's often use.

**Comment by sunnysideup** [comment]
What about this:

![image](https://user-images.githubusercontent.com/167154/52602254-cd0b8f80-2ec6-11e9-9f14-1ebc8cc1884f.png)

CSS is below for your reference ... 

```css

fieldset.grid.grid-field.ss-gridfield.field
{
    border-radius: 5px;
    border: 1px solid rgba(219, 224,233, 1);
    background-color: #f1f3f6!important;
    padding: 10px!important;
}

fieldset.grid.grid-field.ss-gridfield.field .toolbar--content {
    margin-top: 0!important;
}
fieldset.grid.grid-field.ss-gridfield.field .grid-field__title-row .pull-xs-right {display: none;}

fieldset.grid.grid-field.ss-gridfield.field table
{
    min-width: 100%!important;
    margin-left: 0!important;
    margin-right: 0!important;

}

fieldset.grid.grid-field.ss-gridfield.field .sortable-header th {
    background-color: rgba(219, 224,233, 0.7);
}
fieldset.grid.grid-field.ss-gridfield.field .sortablerowsheading {
    line-height: 1!important;
    padding-top: 5px!important;
    padding-bottom: 5px!important;
    background-color: rgba(219, 224,233, 0.7);

}

fieldset.grid.grid-field.ss-gridfield.field tfoot td {
    line-height: 1!important;
    padding-top: 1rem!important;
    padding-bottom: 0!important;
}
```
