### ISSUE TITLE
multiple legacy.yml files do not work together

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#8716]
## Affected Version

SS4.3

## Description

In the upgrade code, it is recommend to create the following file:

legacy.yml:
```yml
SilverStripe\ORM\DatabaseAdmin:
  classname_value_remapping:
    ImageGalleryPage: Sunnysideup\ImageGalleryBasic\ImageGalleryPage
    ImageGalleryPageController: Sunnysideup\ImageGalleryBasic\ImageGalleryPageController
    ImageGalleryHolder: Sunnysideup\ImageGalleryBasic\ImageGalleryHolder
    ImageGalleryHolderController: Sunnysideup\ImageGalleryBasic\ImageGalleryHolderController
    ImageGalleryEntry: Sunnysideup\ImageGalleryBasic\Model\ImageGalleryEntry
```
That works great. However, I have ten modules that I am upgrading for this project, each with their own legacy.yml file.  For some strange reason only one of the legacy.yml file values are used (the other ones, it appears, are overridden). 

It seems to me that you should be able to add a `legacy.yml` to any module so that, when people upgrade to SS4 their database tables are automatically updated.

I dont really understand why the arrays are not merged into one big list of value remapping for tables.  I also dont know how to accomplish this would copying all the legacy.yml entries into one big file (a lot of work). 

## Steps to Reproduce

Create two legacy.yml files in two separate modules (in the _config dir).  

To each, you add a few lines, similar to this:
```yml
SilverStripe\ORM\DatabaseAdmin:
  classname_value_remapping:
    Foo: Bar\Bar\Foo
    Foo2: Bar2\Bar2\Foo2
```
Next, you add some debug statements here:

https://github.com/silverstripe/silverstripe-framework/blob/4/src/ORM/DatabaseAdmin.php#L359-L368

You will see that not all the classname_value_remappings are added.

More importantly, the core ones are also replaced.  

All in all, this is a big pain, because it really slows down the upgrade process if you can't just have the legacy files with each module to do the whole database upgrade at once.
