### ISSUE TITLE
Non-versioned-segmented caches are configured incorrectly

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#8754]
https://docs.silverstripe.org/en/4/changelogs/4.2.0/#versioned-cache-segmentation states that to disable versioned cache segmentation, caches should be configured like:

```yml
SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.myapp:
    factory: SilverStripe\Core\Cache\CacheFactory     
    constructor:
      namespace: "MyInsensitiveData"
      args:
        disable-container: true
```

This doesn’t work, the caches are still segmented - the following config _does_ prevent segmentation:

```yml
SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.myapp:
    factory: SilverStripe\Core\Cache\CacheFactory     
    constructor:
      namespace: "MyInsensitiveData"
      disable-container: true 
```

This means that most of the core caches are misconfigured: https://github.com/silverstripe/silverstripe-framework/blob/4.3.0/_config/cache.yml
