### ISSUE TITLE
Config rule `envvarset` returns true when env vars are not set

### ISSUE THREAD

**Issue by aNickzz** [silverstripe/silverstripe-framework#9892]
## Affected Version

4.6.2

## Description

In yml configs, the [`envvarset`](https://docs.silverstripe.org/en/4/developer_guides/configuration/configuration/#exclusionary-rules) rule is documented to require an environment variable to be set before allowing the config to load. This does not work.

[The code](https://github.com/silverstripe/silverstripe-framework/blob/4/src/Core/Config/CoreConfigFactory.php#L146) for the rule checks if the env value is `=== false`, however an unset variable is `null`

## Steps to Reproduce

Add the following to a yml config file

```yml
---
Only:
  envvarset: MY_UNSET_VAR
---
Page:
  some_config: "env var is set"
```

Don't add `MY_UNSET_VAR` to your `.env` file.

Display the config value for `Page` `some_config` somehow and see that it is set. (I don't have a code snippet for this as I've been checking the values via xdebug)

## Workaround

I'm wanted to use this to optionally override the SMTP config with the following yml

```yml
---
Only:
  envvarset: SMTP_HOST
After:
  - "#emailconfig"
---
SilverStripe\Core\Injector\Injector:
  Swift_Transport:
    class: Swift_SmtpTransport
    properties:
      Host: "`SMTP_HOST`"
      Port: "`SMTP_PORT`"
      Encryption: tls
    calls:
      Username: [setUsername, ["`SMTP_USERNAME`"]]
      Password: [setPassword, ["`SMTP_PASSWORD`"]]
      AuthMode: [setAuthMode, ["login"]]
```

and `.env`

```env
SMTP_HOST="foo"
SMTP_PORT="bar"
SMTP_USERNAME="baz"
SMTP_PASSWORD="qux"
```

The workaround is to replace `envvarset: SMTP_HOST` with

```yml
  envvarset:
    USE_SMTP: "true"
```

and add this to `.env`

```env
# USE_SMTP="true"
SMTP_HOST="foo"
SMTP_PORT="bar"
SMTP_USERNAME="baz"
SMTP_PASSWORD="qux"
```
